# This workflow will check, test and pack the source code, then publish to npm when a release is created
# For more information see: https://viteplus.dev/guide/

name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - run: vp check
      - run: vp test
      - run: vp pack

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          check-latest: true
          registry-url: https://registry.npmjs.org/
          scope: "@vzn"
          cache: true
      - run: vp install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
